using System;
using System.Collections.Generic;
using UnityEngine;

// ReSharper disable CheckNamespace

namespace GameLovers.UiService
{
	/// <summary>
	/// Represents a configuration of an <seealso cref="UiPresenter"/> with all it's important data
	/// The Id is the int representation of the UI generated by the UiIdsGenerator code generator
	/// </summary>
	[Serializable]
	public struct UiConfig
	{
		public string AddressableAddress;
		public int Layer;
		public Type UiType;
		public bool LoadSynchronously;
	}

	/// <summary>
	/// ScriptableObject tool to import the <seealso cref="UiConfig"/> & <seealso cref="UiSetConfig"/> to be used in the <see cref="IUiService"/>
	/// </summary>
	[CreateAssetMenu(fileName = "UiConfigs", menuName = "ScriptableObjects/Configs/UiConfigs")]
	public class UiConfigs : ScriptableObject//, IConfigsContainer<UiConfig>
	{
		[SerializeField]
		private List<UiConfigSerializable> _configs = new List<UiConfigSerializable>();
		[SerializeField]
		private List<UiSetConfigSerializable> _sets = new List<UiSetConfigSerializable>();

		/// <summary>
		/// Gets or sets the list of UI configurations
		/// </summary>
		public List<UiConfig> Configs
		{
			get { return _configs.ConvertAll(element => (UiConfig)element); }
			set { _configs = value.ConvertAll(element => (UiConfigSerializable)element); }
		}

		/// <summary>
		/// Gets the list of UI set configurations
		/// </summary>
		public List<UiSetConfig> Sets => _sets.ConvertAll(element => UiSetConfigSerializable.ToUiSetConfig(element, _configs));

		/// <summary>
		/// Sets the new size of this scriptable object <seealso cref="UiSetConfig"/> list.
		/// The UiConfigSets have the same id value that the index in the list
		/// </summary>
		/// <param name="size">The new size of the list</param>
		public void SetSetsSize(int size)
		{
			if (size < _sets.Count)
			{
				_sets.RemoveRange(size, _sets.Count - size);
			}

			for (int i = 0; i < size; i++)
			{
				if (i < _sets.Count)
				{
					var cleanedConfigList = new List<string>(_sets[i].UiConfigsAddress.Count);

					foreach (var address in _sets[i].UiConfigsAddress)
					{
						if (_configs.FindIndex(config => config.AddressableAddress == address) > -1)
						{
							cleanedConfigList.Add(address);
						}
					}

					var set = _sets[i];
					set.UiConfigsAddress = cleanedConfigList;
					_sets[i] = set;
					continue;
				}

				_sets.Add(new UiSetConfigSerializable { SetId = i, UiConfigsAddress = new List<string>() });
			}
		}

		/// <summary>
		/// Necessary to serialize the data in scriptable object
		/// </summary>
		[Serializable]
		public struct UiConfigSerializable
		{
			public string AddressableAddress;
			public int Layer;
			public string UiType;

			public static implicit operator UiConfig(UiConfigSerializable serializable)
			{
				return new UiConfig
				{
					AddressableAddress = serializable.AddressableAddress,
					Layer = serializable.Layer,
					UiType = Type.GetType(serializable.UiType),
					LoadSynchronously = false
				};
			}

			public static implicit operator UiConfigSerializable(UiConfig config)
			{
				return new UiConfigSerializable
				{
					AddressableAddress = config.AddressableAddress,
					Layer = config.Layer,
					UiType = config.UiType.AssemblyQualifiedName
				};
			}
		}

	}
}